### ISSUE TITLE
MediaWiki skin ready to roll out

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/MediaWiki_Skin_57n#1]
Hi Iain
This is ready to go I think.  Do you want to put it on https://wiki.57north.org.uk or let me know how that can be done.

Thanks
Andy

@irl

**Comment by irl** [comment]
On 21/10/18 23:38, Andy Gaskell wrote:
> Hi Iain
> This is ready to go I think. Do you want to put it on
> https://wiki.57north.org.uk or let me know how that can be done.

I will hopefully look at this this week.

**Comment by AndyGaskell** [comment]
Thanks @irl let me know if you have any feedback or need a hand.  Installation notes are in the  	README.md, it should be pretty straight forward.
Does it just sit on a VM from OVH?  I'm happy to install it if you're ok sharing the credentials.

**Comment by AndyGaskell** [comment]
Nudge @irl  :)

**Comment by AndyGaskell** [comment]
Thanks Iain :)
